stages:
  - build

variables:
  APPLICATION_NAME: haproxy-updater
  REPOSITORY_NAME: ${APPLICATION_NAME}
  CONTAINER_IMAGE: ${AWS_ECR_URL}/${REPOSITORY_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CI_COMMIT_SHORT_SHA}

build:
  stage: build
  only:
    - master
  before_script:
    - >
      aws ecr create-repository --repository-name ${REPOSITORY_NAME}
      || echo "Repository might have already existed"
  script:
    - docker build -t ${CONTAINER_IMAGE_TAGGED} .
    - docker push ${CONTAINER_IMAGE_TAGGED}

